Main test spec
SunnyAsar/Testing-Enumerable-Methods pull request #1
Opened 2019-04-11 20:17 UTC by SunnyAsar

2019-04-11 21:06 UTC, inhaq requested changes
Hi, Good work. Your tests are running smooth but check out comments to follow best practices and will be helpful in the future. Kindly update and resubmit for review.

2019-04-11 21:06 UTC, inhaq commented on spec/main_test_spec.rb
> +  context '#my_count' do
[Check](http://www.betterspecs.org/#contexts) the good practices of `context` and update accordingly

2019-04-11 21:06 UTC, inhaq commented on spec/main_test_spec.rb
> +  array = [1, 2, 3, 4, 5]
Use `let` instead of local variable, how? [check it here](http://www.betterspecs.org/#let)

2019-04-12 07:57 UTC, inhaq approved these changes
Good job with learning `rspec` best practices. 👍🏻for the project. Go ahead and submit a project completion form.

2019-04-12 17:10 UTC, SunnyAsar commented
thanks for the review @inhaq

2019-04-12 17:10 UTC, merged